# Generated by Django 3.1.3 on 2020-11-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodlyuser',
            managers=[
            ],
        ),
    ]
