# Generated by Django 3.1.3 on 2020-12-15 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.PositiveIntegerField()),
                ('food', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
