# Generated by Django 3.1.3 on 2020-12-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Restaurant Name')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('map_url', models.URLField(max_length=2000, verbose_name='Google Map Url')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Food Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant')),
            ],
        ),
    ]
